### PR TITLE
Add embedded policies to the Role resource

### PR DESCRIPTION
**Pull request by manelmontilla**
By now, Altimeter only retrieves the attached policies of a role, but not the embedded ones.
This PR adds a new ListField to IAM role resources named Embedded Policy.
The field is populated with the name and the document text of each embedded policy of the the role.

### CODE REVIEW

**Comment by jbmchuck** [comment]
Thanks for the contribution! LGTM however as this does add an additional API call I'll need to let a test build bake in our dev env for a bit to ensure it doesn't result in api limit exceptions in a large env.

In the meantime could you run 19.10b0 against the updated files and verify tox passes? I've fixed the ci in master such that from here on new PRs will trigger this as a github action.

**Comment by jbmchuck** [comment]
@manelmontilla here's a PR into your fork+branch after running black: https://github.com/manelmontilla/altimeter/pull/4

**Comment by manelmontilla** [comment]
Thanks for making the PR I will merge it push upstream.

**Comment by jbmchuck** [comment]
Thanks - LGTM

**Comment by jbmchuck** [comment]
This is available in 6.3.10

**Pull request merged**
